apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  POSTGRES_DB: "mydatabase"
  POSTGRES_USER: "myuser"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-pwd
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==